Quote/urls.py
from django.conf.urls import url

from Quote.views import QuoteCreta
from .views import Index, QuoteCreate, QuoteView, AddItem, ItemDelete


urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', QuoteView.as_view(), name='quote'),
    url(r'^create/', QuoteCreta.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/add', AddItem.as_view(), name='add_item'),
    url(r'^(?P<pk>[0-9]+)/delete/(?P<id>[0-9]+)', ItemDelete.as_view(), name='delete_item')
]

Site/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls.base import reverse_lazy
from .settings import LOGIN_URL
from django.contrib.auth.decorators import user_passes_test

login_forbidden = user_passes_test(lambda u: u.is_anonymous(), reverse_lazy('index'), redirect_field_name=None)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_forbidden(auth_views.login), {'template_name': 'Quote/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': LOGIN_URL}, name='logout'),
    url(r'^quotes/', include('Quote.urls')),
]

Quote/models.py
from django.db import models
from django.shortcuts import reverse


class Quote(models.Model):
    company_name = models.CharField(max_length=100)
    attention = models.CharField(max_length=100)
    job = models.CharField(max_length=100)
    date = models.DateField()
    site = models.CharField(max_length=100)
    total = models.FloatField(default=0)

    def __str__(self):
        return self.company_name + '-' + str(self.date)

    def get_absolute_url(self):
        return reverse('add_item', kwargs={'pk': self.id})


class Item(models.Model):
    HEAVY_DUTY_CUPLOCK = 'HDC'
    ALUMINIUM = 'AL'
    CORE_CUTTING = 'CRC'
    CONCRETE_CUTTING = 'CTC'
    SCAFFOLDING = 'SF'
    ITEM_CHOICES = (
        (HEAVY_DUTY_CUPLOCK, 'Heavy Duty Cuplock'),
        (ALUMINIUM, 'Aluminium'),
        (CORE_CUTTING, 'Core Cutting'),
        (CONCRETE_CUTTING, 'Concrete Cutting'),
        (SCAFFOLDING, 'Scaffolding'),
    )
    item = models.CharField(choices=ITEM_CHOICES, max_length=3, null=True)
    description = models.CharField(max_length=200)
    unit_price = models.FloatField()
    quantity = models.IntegerField()
    hiring_days = models.IntegerField(null=True)
    total = models.FloatField()
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.total:
            self.total = self.unit_price * self.quantity
        self.quote.total += self.total
        self.quote.save()
        return super(Item, self).save()

    def delete(self, using=None, keep_parents=False):
        self.quote.total -= self.total
        self.quote.save()
        return super(Item, self).delete()

    def get_absolute_url(self):
        return reverse('add_item', kwargs={'pk': self.quote.id})


class Terms(models.Model):
    terms = models.TextField(max_length=5000)

    def __str__(self):
        return self.terms

Quote/forms.py
from django import forms
from .models import Quote, Item, Terms


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        exclude = ['total']


class ItemForm(forms.ModelForm):
    hiring_days = forms.IntegerField(required=False, label='Days')
    quantity = forms.IntegerField(label='QTY')
    unit_price = forms.FloatField(label='Price')

    class Meta:
        model = Item
        exclude = ['quote']


class TermsForm(forms.ModelForm):
    terms = forms.CharField(initial=Terms.objects.get(id=1).terms, widget=forms.Textarea)

    class Meta:
        model = Terms
        fields = ['terms']

Quote/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.views.generic.base import View
from Quote.forms import TermsForm
from Quote.models import Terms
from .forms import QuoteForm, ItemForm
from .models import Quote, Item
from django.shortcuts import reverse, render


class Index(ListView):
    queryset = Quote.objects.all().order_by('-id')[:10]
    template_name = 'Quote/quotes.html'


class QuoteView(DetailView):
    template_name = 'Quote/quote.html'
    model = Quote

    def get_context_data(self, **kwargs):
        context = super(QuoteView, self).get_context_data()
        context['terms'] = Terms.objects.get(id=1)
        return context


class QuoteCreate(CreateView):
    form_class = QuoteForm
    model = Quote
    template_name = 'Quote/create.html'


class QuoteCreta(View):
    form_class = QuoteForm
    form_class1 = TermsForm
    template_name = 'Quote/create.html'
    terms = Terms.objects.get(id=1)

    def get_success_url(self, pk):
        return reverse('add_item', kwargs={'pk': pk})

    def get(self, request):
        form1 = self.form_class(None)
        form2 = self.form_class1(None)
        return render(request, self.template_name, {'form1': form1, 'form2': form2})

    def post(self, request):
        form1 = self.form_class(request.POST)
        form2 = self.form_class1(request.POST)

        if form1.is_valid():
            obj = form1.save()
            if form2.is_valid():
                self.terms.terms = form2.cleaned_data['terms']
                print(self.terms.terms)
                self.terms.save()
                return HttpResponseRedirect(self.get_success_url(obj.id))
        return render(request, self.template_name, {'form1': form1, 'form2': form2, 'terms': self.terms})


class AddItem(CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'Quote/add_items.html'

    def get_context_data(self, **kwargs):
        context = super(AddItem, self).get_context_data(**kwargs)
        context['quote'] = Quote.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        quote = Quote.objects.get(id=self.kwargs['pk'])
        self.object.quote = quote
        return super(AddItem, self).form_valid(form)

    def get_success_url(self):
        return reverse('add_item', kwargs={'pk': self.object.quote.id})


class ItemDelete(DeleteView):
    model = Item

    def get_object(self, queryset=None):
        return self.model.objects.get(id=self.kwargs['id'])

    def get_success_url(self):
        return reverse('add_item', kwargs={'pk': self.object.quote.id})

templates/Quote/add_items.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="container">
    <div class="card">
        <div class="card-content">
            <a href="{% url 'quote' quote.id %}" class="btn right" style="background-color: rgba(58,186,82,0.78);">View Quotation</a>
        <div class="card-title">{{ quote }}</div>
            <form id="items-form" method="post">
        <div class="row" style="margin: 20px 0 0 0">
            {% csrf_token %}
            {% for field in form %}
                {% if not forloop.counter > 2 %}
                <div class="input-field col s3" style="min-width: 80px">
                    {% render_field field id=field.label|lower %}
                    <label for="{{ field.label|lower }}">{{ field.label }}</label>
                </div>
                {% else %}
                <div class="input-field col s1" style="min-width: 80px">
                    {% render_field field id=field.label|lower %}
                    <label for="{{ field.label|lower }}">{{ field.label }}</label>
                </div>
                {% endif %}
            {% endfor %}
        <button class="btn-large right" style="background-color: #304ffe; margin: 5px 0" type="submit">ADD</button>
        </div>
        </form>
        </div>
    </div>
    <div class="card" style="height: auto">
    <div class="card-content">
        <div class="card-title">Items</div>
        <table class="responsive-table" style="margin: 20px 0">
            <thead>
            <tr>
                <th>S. No.</th>
                <th>ITEM</th>
                <th>DESCRIPTION</th>
                <th>UNIT PRICE</th>
                <th>QTY</th>
                <th>HIRING DAYS</th>
                <th>TOTAL IN AED</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for item in quote.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.get_item_display }}</td>
                <td>{{ item }}</td>
                <td>{{ item.unit_price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.hiring_days }}</td>
                <td>{{ item.total }}</td>
                <td><form method="post" action="{% url 'delete_item' quote.id item.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn red">Delete</button>
                </form> </td>
            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th class="center" colspan="6">TOTAL</th>
                <th colspan="1">{{ quote.total }}</th>
            </tr>
            </tfoot>
            <tr></tr>
        </table>
    </div>
    </div>
    </div>
<script>
  $(document).ready(function() {
    $('select').material_select();
  });
</script>
{% endblock %}

templates/Quote/create.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block body %}
    <div class="container">
    <div class="row center">
    <div class="card col s8 offset-s2">
    <div class="card-content">
        <div class="card-title">New Quotation</div>
        <div class="row">
            <form method="post">
                {% csrf_token %}
                {% with form1 as form %}
        {% include 'form_template.html' %}
                {% endwith %}

            <div class="input-field col s12 center">
                <h5>{{ form2.terms.label }}</h5>
                    {% render_field form2.terms id=field.label|lower %}
            </div>
                <button title="submit" class="btn blue right">Proceed</button>
            </form>
        </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/Quote/login.html
{% extends 'index.html' %}
{% block title %}Login{% endblock %}
{% block body %}
    {% load staticfiles %}
    	<div class="container">
		<div class="center">
            <h3 id="title" class="hidden"><span id="logo"><span style="font-weight: bolder">Icon</span> <span>Scaffoldings</span></span></h3>
		</div>
        <div class="center">
		<div class="card fadeInUp">
        <div class="card-panel">
			<div class="box-header">
				<h4>Log In</h4>
			</div>
            {% for field in form %}

            <form role="form" method="post">
                <div class="'col s10">
                <span class="text-danger small">{{ field.error }}</span>
            </div>
            {% csrf_token %}
            <label for="exampleInputEmail1">
            {{ field.label_tag }}
            </label>
            <div class="col l12">{{ field }}</div>
            {% endfor %}
			<!--<button class="btn btn-default" type="submit">Sign In</button>-->
            <div>
            <button class="btn btn-default" type="submit">Login</button>
            </div>
			<br/>
            </form>
		    </div>
	        </div>
        </div>
        </div>
{% endblock %}

templates/Quote/quote.html
{% extends 'index.html' %}
{% load static %}
{% block nav %}
{% endblock %}
{% block title %}
    {{ quote }}
{% endblock %}
{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'quotestyle.css' %}">
<div class="row" style="position: relative; padding: 10px 10px 10px 20px">
    <img src="{% static 'img/header.jpg' %}" style="max-width: 100%; width: 100%">
    <h4 class="center">Quotation</h4>
        <table>
            <tr>
                <th>COMPANY NAME</th>
                <td>{{ quote.company_name }}</td>
            </tr>
            <tr>
                <th>ATTENTION</th>
                <td>{{ quote.attention }}</td>
            </tr>
            <tr>
                <th>JOB</th>
                <td>{{ quote.job }}</td>
            </tr>
            <tr>
                <th>DATE</th>
                <td>{{ quote.date|date:'d/m/y' }}</td>
            </tr>
            <tr>
                <th>SITE</th>
                <td>{{ quote.site }}</td>
            </tr>
        </table>
        <p style="margin: 10px 5px;">
            Dear Sir, with reference to the enquiry dated 23/04/2017 for core hole, we are pleased to quote our best offer as under.
        </p>
        <table style="margin: 20px 0">
            <thead>
            <tr>
                <th>S. No.</th>
                <th>ITEM</th>
                <th>DESCRIPTION</th>
                <th>UNIT PRICE</th>
                <th>QTY</th>
                <th>HIRING DAYS</th>
                <th>TOTAL IN AED</th>
            </tr>
            </thead>
            <tbody>
            {% for item in quote.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.get_item_display }}</td>
                <td>{{ item }}</td>
                <td>{{ item.unit_price }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.hiring_days }}</td>
                <td>{{ item.total }}</td>
            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th class="center" colspan="6">TOTAL</th>
                <th colspan="1">{{ quote.total }}</th>
            </tr>
            </tfoot>
            <tr></tr>
        </table>
        <div style="z-index: 100" id="terms">
            <h6 style="font-weight: bolder; font-size: large">TERMS AND CONDTIONS</h6>
            {{ terms | safe }}
        </div>
    <div class="footer">
        <p>
            For further clarification please contact the undersigned
        </p>
        <p>
            For ICON SCAFFOLDING RENTAL LLC
        </p>
        <img style="position: absolute; right: 20px; bottom: 20px; width: 250px" src="{% static 'img/seal.png' %}">
            <h4 class="sign" style="position: absolute; right: 250px; bottom: 100px">Azeem</h4>
        <p>
            +97155 3359645, 056 4419367
        </p>
    </div>
</div>
{% endblock %}

templates/Quote/quotes.html
{% extends 'index.html' %}
{% block body %}
<div class="card">
<div class="card-content">
    <a class="btn blue right" href="{% url 'create' %}">New Quotation</a>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Quote</th>
            <th>Date</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for quote in object_list %}
            <tr>
            <td>{{ quote.id }}</td>
            <td><a href="{% url 'quote' quote.id %}">{{ quote }}</a></td>
            <td>{{ quote.date }}</td>
            <td><a href="{% url 'add_item' quote.id %}">Edit</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

templates/form_template.html
{% load widget_tweaks %}
           {% for field in form %}
                {% if field|field_type == 'booleanfield' %}
                    <div class="input-field col s12">
                    {% render_field field %}
                    <label for="id_{{ field.label }}">{{ field.label }}</label>
                    </div>
                {% elif field.label == 'Description' %}
                    <div class="input-field col s12">
                        {% render_field field class="materialize-textarea" %}
                        <label for="id_{{ field.label }}">{{ field.label }}</label>
                    </div>
                {% elif field|field_type == 'imagefield' %}
                    <div>
                    <div class="file-field input-field col s12">
                    <div class="btn">
                        <span>IMAGE</span>
                            {% render_field field type='file' %}
                        </div>
                    <div class="file-path-wrapper">
                        {% render_field field class="file-path validate" type='text' %}
                    </div>
                        </div>
                    </div>
                {% elif field|field_type == 'datefield' %}
                    <div class="input-field col s12">
                    {% render_field field type='date' class='datepicker' id=field.label|lower %}
                    <label for="{{ field.label|lower }}">{{ field.label }}</label>
                    </div>
                    {% else %}
                <div class="input-field col s12">
                    {% render_field field id=field.label|lower %}
                <label for="{{ field.label|lower }}">{{ field.label }}</label>
                </div>
                {% endif %}
           {% endfor %}
<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year
    format: 'm/d/yyyy'
  });
</script>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>{% block title %}Quotes{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
    <script>tinymce.init({
        selector:'textarea',
        theme: 'modern',
        plugins: [
                'advlist autolink lists link image charmap print preview hr anchor',
        ]
    });</script>
    <script rel="script" src="{% static 'js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>

{% block script %}{% endblock %}
</head>
<body>
{% block nav %}
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'index' %}" class="brand-logo center">Quotes</a>
      <ul id="nav-mobile" class="right">
        <li class="tooltipped" data-tooltip="Logout" data-position="bottom" data-delay="50"><a href="{% url 'logout' %}"><i class="material-icons left">power_settings_new</i></a></li>
      </ul>
    </div>
  </nav>

</div>
{% endblock %}
{% block body %}
{% endblock %}
</body>
</html>